import Head from "next/head";
import React from "react";
import NavbarComponent from "~/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full w-screen flex-col items-center bg-gradient-to-b from-[#000] to-[#15162c] py-4">
        <NavbarComponent />
        <div className="relative z-[50] mb-4 grid w-[90vw] grid-cols-2 gap-4 pt-4">
          <div className="col-span-2 flex h-[25vh] justify-center border"></div>
          <div className="col-span-1 flex h-[70vh] flex-col space-y-4 rounded-3xl bg-slate-500/10 p-4 text-white">
            <p className="text-sm font-bold">Existing Components</p>
            <h1 className="font-bold leading-[1em] [font-size:_clamp(2em,2vw,8em)]">
              Free
            </h1>
          </div>
          <div className="col-span-1 flex h-[70vh] flex-col space-y-4 rounded-3xl bg-slate-500/10 p-4 text-white">
            <p className="text-sm font-bold">Custom Components</p>
            <div>
              <p className="text-sm">Starting at</p>
              <h1 className="font-bold leading-[1em] [font-size:_clamp(2em,2vw,8em)]">
                $1500/Component
              </h1>
            </div>
          </div>
          <div className="col-span-1 flex h-[70vh] flex-col space-y-4 rounded-3xl bg-slate-500/10 p-4 text-white">
            <p className="text-sm font-bold">Multi Page Website</p>
            <div>
              <p className="text-sm">Starting at</p>
              <h1 className="font-bold leading-[1em] [font-size:_clamp(2em,2vw,8em)]">
                $9000
              </h1>
            </div>
          </div>
          <div className="col-span-1 flex h-[70vh] flex-col space-y-4 rounded-3xl bg-slate-500/10 p-4 text-white">
            <p className="text-sm font-bold">Multi Page Website</p>
            <div>
              <p className="text-sm">Starts at</p>
              <h1 className="font-bold leading-[1em] [font-size:_clamp(2em,2vw,8em)]">
                $9000
              </h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
